-- Marketing Proposal Generator - Supabase setup
-- Run this once in Supabase > SQL Editor before enabling cloud mode.

create table if not exists public.proposals (
    id bigint generated by default as identity primary key,
    proposal_name text not null,
    credit_union text not null,
    proposal_type text not null,
    msr text default '',
    status text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    saved_data_json jsonb not null default '{}'::jsonb,
    updated_by text,
    locked_by text,
    locked_at timestamptz,
    copied_from_proposal_id bigint references public.proposals(id) on delete set null
);

create index if not exists proposals_updated_at_idx on public.proposals(updated_at desc);
create index if not exists proposals_credit_union_idx on public.proposals(credit_union);
create index if not exists proposals_status_idx on public.proposals(status);

create table if not exists public.pricing_settings (
    key text primary key,
    category text not null,
    label text not null,
    value numeric not null,
    value_type text not null default 'currency',
    unit text default '',
    description text default '',
    sort_order integer default 0,
    is_repeating boolean not null default false,
    active boolean not null default true,
    updated_at timestamptz,
    updated_by text
);

create table if not exists public.pricing_history (
    id bigint generated by default as identity primary key,
    setting_key text not null,
    old_value numeric,
    new_value numeric not null,
    old_is_repeating boolean,
    new_is_repeating boolean,
    old_active boolean,
    new_active boolean,
    changed_at timestamptz not null default now(),
    changed_by text
);

create index if not exists pricing_history_changed_at_idx on public.pricing_history(changed_at desc);

create table if not exists public.proposal_pricing_snapshots (
    id bigint generated by default as identity primary key,
    proposal_id bigint not null references public.proposals(id) on delete cascade,
    generated_at timestamptz not null default now(),
    generated_by text,
    pricing_json jsonb not null
);

create index if not exists pricing_snapshots_proposal_idx
    on public.proposal_pricing_snapshots(proposal_id, generated_at desc);

-- Keep these tables private from browser/anonymous clients. The Streamlit backend should use
-- its server-side Supabase key stored only in Streamlit Secrets.
alter table public.proposals enable row level security;
alter table public.pricing_settings enable row level security;
alter table public.pricing_history enable row level security;
alter table public.proposal_pricing_snapshots enable row level security;

-- Private bucket for PPTX/CSV artifacts. The app can also create it automatically when using
-- a server-side key with sufficient permissions.
insert into storage.buckets (id, name, public)
values ('proposal-files', 'proposal-files', false)
on conflict (id) do nothing;
